controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /api/auth
    methods: ["POST"]

protected_route:
    path: /api/protected-route
    controller: App\Controller\ProtectedController::protectedRoute
    methods: GET
